# Generated by Django 5.1.3 on 2024-11-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='street',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
